### PR TITLE
Support JS IR in plugin

### LINKED ISSUE #30: Turn on JS IR
I'm having such an error because the runtime library doesn't support JS IR.

```
Caused by: org.gradle.internal.component.NoMatchingConfigurationSelectionException: No matching variant of org.jetbrains.kotlinx:kotlinx.benchmark.runtime:0.2.0-dev-20 was found. The consumer was configured to find a usage of 'kotlin-runtime' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js', attribute 'org.jetbrains.kotlin.js.compiler' with value 'ir' but:
  - Variant 'js-api' capability org.jetbrains.kotlinx:kotlinx.benchmark.runtime:0.2.0-dev-20 declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js':
 ```

### PR DESCRIPTION
**Pull request by whyoleg**
* fixes #30 
* suppresses #31
* TODO `ms` time units fails on IR

### CODE REVIEW

**Comment by whyoleg** [comment]
It works for both IR and Legacy JS compilers, but looks like there is an issue with JS IR produced js code. Here is the same code compiled with Legacy and IR:
source:
```kotlin
private fun parseTimeUnit(text: String) = when (text) {
    BenchmarkTimeUnit.SECONDS.name, "s", "sec" -> BenchmarkTimeUnit.SECONDS
    BenchmarkTimeUnit.MICROSECONDS.name, "us", "micros" -> BenchmarkTimeUnit.MICROSECONDS
    BenchmarkTimeUnit.MILLISECONDS.name, "ms", "millis" -> BenchmarkTimeUnit.MILLISECONDS
    BenchmarkTimeUnit.NANOSECONDS.name, "ns", "nanos" -> BenchmarkTimeUnit.NANOSECONDS
    BenchmarkTimeUnit.MINUTES.name, "m", "min" -> BenchmarkTimeUnit.MINUTES
    else -> throw UnsupportedOperationException("Unknown time unit: $text")
}
```
Legacy:
```js
RunnerConfiguration.prototype.parseTimeUnit_0 = function (text) {
  if (equals(text, BenchmarkTimeUnit$SECONDS_getInstance().name) || equals(text, 's') || equals(text, 'sec'))
    return BenchmarkTimeUnit$SECONDS_getInstance();
  else if (equals(text, BenchmarkTimeUnit$MICROSECONDS_getInstance().name) || equals(text, 'us') || equals(text, 'micros'))
    return BenchmarkTimeUnit$MICROSECONDS_getInstance();
  else if (equals(text, BenchmarkTimeUnit$MILLISECONDS_getInstance().name) || equals(text, 'ms') || equals(text, 'millis'))
    return BenchmarkTimeUnit$MILLISECONDS_getInstance();
  else if (equals(text, BenchmarkTimeUnit$NANOSECONDS_getInstance().name) || equals(text, 'ns') || equals(text, 'nanos'))
    return BenchmarkTimeUnit$NANOSECONDS_getInstance();
  else if (equals(text, BenchmarkTimeUnit$MINUTES_getInstance().name) || equals(text, 'm') || equals(text, 'min'))
    return BenchmarkTimeUnit$MINUTES_getInstance();
  else
    throw UnsupportedOperationException_init('Unknown time unit: ' + text);
};
```
IR:
```js
function parseTimeUnit($this, text) {
  var tmp0_subject = text;
  var tmp;
  switch (tmp0_subject) {
    case 'sec':
      tmp = BenchmarkTimeUnit_SECONDS_getInstance();
      break;
    case 'micros':
      tmp = BenchmarkTimeUnit_MICROSECONDS_getInstance();
      break;
    case 'millis':
      tmp = BenchmarkTimeUnit_MILLISECONDS_getInstance();
      break;
    case 'nanos':
      tmp = BenchmarkTimeUnit_NANOSECONDS_getInstance();
      break;
    case 'min':
      tmp = BenchmarkTimeUnit_MINUTES_getInstance();
      break;
    default:throw UnsupportedOperationException_init_$Create$_0('' + 'Unknown time unit: ' + text);
  }
  return tmp;
}
```

Seems it's better to report it to youtrack? Or is there an issue already created? Haven't found it by fast search

**Comment by whyoleg** [comment]
@qurbonzoda can you take a look?

**Comment by whyoleg** [comment]
@qurbonzoda Any news on PR review? If it's ok, I will update `parseTimeUnit` code to workaround bug mentioned in the comment

**Comment by qurbonzoda** [comment]
@whyoleg, Sorry for the long absence. I was busy with Kotlin 1.5.0 release. Will review the changes in the coming few days.

**Comment by whyoleg** [comment]
As next release of the kotlinx.benchmark will be after 1.5.0 release, may be it will be better to update kotlin version first, and after that review this PR, as how I understand, it uses some half-internal APIs to extract data from klibs, that can be broken/changed in 1.5.0 :)
So, will you, @qurbonzoda update it to 1.5.0 soon? Or I can do it in one of coming days (as 1.5.0 is already somewhere on maven central)?

**Comment by whyoleg** [comment]
@qurbonzoda any news ?

**Comment by qurbonzoda** [comment]
@whyoleg Yes, Kotlin 1.5.0 is released and we can update the Kotlin version to 1.5.0.
Please feel free to update it, in a separate PR.

**Comment by CommanderTvis** [comment]
@qurbonzoda Any news?

**Comment by olme04** [comment]
@qurbonzoda Any news on when this could be merged?

**Comment by olme04** [comment]
@qurbonzoda any news, when this could me merged?
Or f.e. if someone will actualize it, will it be merged faster?

**Comment by olme04** [comment]
@qurbonzoda no problem, look at #64 :)

**Comment by qurbonzoda** [comment]
The updated version of this implementation was merged: #64.
Thank you for the effort!

**Pull request closed without merging**
